### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by zmitic** [smorenost/first-#1]
- Don't use non-english names
- Please use ``templates/index.html`` file as it was so we have a history of that file
- Make proper formatting (CTRL+Alt+L in Storm)
- ``float: center`` doesn't exist

![image](https://user-images.githubusercontent.com/1964158/95090133-350a8b80-0725-11eb-835e-96c19a31c6c5.png)

- Install PHPStorm/Webstorm; it will verify your work for you
- It is ``vertical-text``, not ``vericaltext``; no separator, missing letter **t**. These things are super-important.

Take a look at this screenshot:

![image](https://user-images.githubusercontent.com/1964158/95090714-e0b3db80-0725-11eb-9308-1dcd067a35ae.png)

You can see errors at top-right.

**Comment by zmitic** [comment]
Few clues in using PHP/web storm:

- formatting: CTRL+Alt+L
- Errors: put cursor inside the problem, press Alt+Enter. All options are there
- See files changed:

![image](https://user-images.githubusercontent.com/1964158/95091792-2c1ab980-0727-11eb-8fc5-9f9b1ee98b56.png)

- these 3 icons are for git, should have been autoconfigured by now:

![image](https://user-images.githubusercontent.com/1964158/95091900-4f456900-0727-11eb-8a80-cd85ef8e0d83.png)

**Comment by smorenost** [comment]
[
![solution 2](https://user-images.githubusercontent.com/72141144/95139282-6a869780-076c-11eb-86d2-6362a0070a1c.PNG)
![solution](https://user-images.githubusercontent.com/72141144/95139285-6b1f2e00-076c-11eb-9d57-8a1a6679038a.PNG)

](url)
